name: "Setup Docker on macOS"
description: "Setup Docker on macOS using Colima, Lima-VM, and Homebrew."
outputs:
  colima-version:
    value: ${{ steps.colima-version.outputs.version }}
    description: Version of Colima
  docker-client-version:
    value: ${{ steps.docker-client-version.outputs.version }}
    description: Version of the Docker client
runs:
  using: "composite"
  steps:
    - name: Safety check
      if: runner.os != 'macOS'
      run: |
        echo "Not a macOS runner, exiting."
        exit 1
      shell: bash
    - name: Update Homebrew
      run: |
        brew update --preinstall
      shell: bash
    - name: Pre-cache
      run: |
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/colima.rb" > .github/brew-colima
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/docker.rb" > .github/brew-docker
        brew_cellar="$(brew --cellar)"
        echo "BREW_CELLAR="$brew_cellar"" >> $GITHUB_ENV
        brew_cache_list=$(brew deps colima | while read line; do echo "$brew_cellar/$line"; done)
        echo "BREW_CACHE_LIST="$brew_cache_list"" >> $GITHUB_ENV
        echo $brew_cache_list > .github/brew-colima-deps
      shell: bash
    - name: Configure Homebrew cache
      id: cache-homebrew
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.BREW_CACHE_LIST }}
          ${{ env.BREW_CELLAR }}/docker
        key: brew-${{ hashFiles('.github/brew-*') }}
        restore-keys: brew-
    - name: Relink and redownload deps for Docker client and Colima
      if: steps.cache-homebrew.outputs.cache-hit == 'true'
      run: |
        brew link docker
        deps=$(brew deps colima | tr '\n' ' ')
        brew link --overwrite --force $deps
      shell: bash
    - name: Install Docker client and Colima
      if: steps.cache-homebrew.outputs.cache-hit != 'true'
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
      run: |
        brew link docker colima || true
        brew install docker colima
      shell: bash
    - name: Start Colima
      run: colima start
      shell: bash
    - id: docker-client-version
      run: |
        content="$(docker version)"
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=version::$content"
      shell: bash
    - id: colima-version
      run: |
        content="$(colima version)"
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=version::$content"
      shell: bash
