name: "Setup Docker on macOS"
description: "Setup Docker on macOS using Colima, Lima-VM, and Homebrew."
outputs:
  colima-version:
    value: ${{ steps.docker-client-version.outputs.version }}
    description: Version of Colima
  docker-client-version:
    value: ${{ steps.colima-client-version.outputs.version }}
    description: Version of the Docker client
runs:
  using: "composite"
  steps:
    - name: Safety check
      if: runner.os != 'macOS'
      run: |
        echo "Not a macOS runner, exiting."
        exit 1
      shell: bash
    - name: Update Homebrew
      run: |
        brew update --preinstall
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/colima.rb" > .github/brew-colima
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/docker.rb" > .github/brew-docker
        cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/qemu.rb" > .github/brew-qemu
      shell: bash
    - name: Pre-cache
      run: echo "BREW_CELLAR=$(brew --cellar)" >> $GITHUB_ENV
      shell: bash
    - name: Configure Homebrew cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.BREW_CELLAR }}/colima
          ${{ env.BREW_CELLAR }}/docker
          ${{ env.BREW_CELLAR }}/qemu
        key: brew-${{ hashFiles('.github/brew-*') }}
        restore-keys: brew-
    - name: Install Docker client and Colima
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
      run: brew install docker colima
      shell: bash
    - id: docker-client-version
      run: echo "::set-output name=version::$(docker version)"
      shell: bash
    - id: colima-version
      run: echo "::set-output name=version::$(colima version)"
      shell: bash
