name: "Setup Docker (Lima-VM)"
description: "Set ups Docker using LimaVM"
outputs:
  colima-version:
    description: Version of Colima
  docker-client-version:
    description: Version of the Docker client
runs:
  using: "node16"
  main: "index.js"
